[
  {
    draws: 8,
    goal_difference: 26,
    logo: "https://static.flashscore.com/res/image/data/6yCLyXU0-ALgHCh57.png",
    losses: 8,
    matches: 34,
    points: 62,
    position: 1,
    team_name: "Palmeiras",
    wins: 18,
  },
  {
    draws: 8,
    goal_difference: 23,
    logo: "https://static.flashscore.com/res/image/data/Esn3EmDN-nu2KFFkD.png",
    losses: 9,
    matches: 35,
    points: 62,
    position: 2,
    team_name: "Botafogo RJ",
    wins: 18,
  },
  {
    draws: 9,
    goal_difference: 19,
    logo: "https://static.flashscore.com/res/image/data/h8ZzOL5k-pCk2vaSD.png",
    losses: 9,
    matches: 35,
    points: 60,
    position: 3,
    team_name: "Atletico-MG",
    wins: 17,
  },
  {
    draws: 9,
    goal_difference: 14,
    logo: "https://static.flashscore.com/res/image/data/8URbBane-2R2JjDQC.png",
    losses: 8,
    matches: 34,
    points: 60,
    position: 4,
    team_name: "Flamengo RJ",
    wins: 17,
  },
  {
    draws: 5,
    goal_difference: 4,
    logo: "https://static.flashscore.com/res/image/data/lnrkBi86-tQsU6dGl.png",
    losses: 12,
    matches: 35,
    points: 59,
    position: 5,
    team_name: "Gremio",
    wins: 18,
  },
  {
    draws: 11,
    goal_difference: 16,
    logo: "https://static.flashscore.com/res/image/data/fXZwgsRq-UkMF8Udb.png",
    losses: 7,
    matches: 34,
    points: 59,
    position: 6,
    team_name: "Bragantino",
    wins: 16,
  },
  {
    draws: 8,
    goal_difference: 3,
    logo: "https://static.flashscore.com/res/image/data/SII56zA6-ALgHCh57.png",
    losses: 12,
    matches: 35,
    points: 53,
    position: 7,
    team_name: "Fluminense",
    wins: 15,
  },
  {
    draws: 13,
    goal_difference: 8,
    logo: "https://static.flashscore.com/res/image/data/INluPVA6-QaMaOfUh.png",
    losses: 9,
    matches: 35,
    points: 52,
    position: 8,
    team_name: "Athletico-PR",
    wins: 13,
  },
  {
    draws: 8,
    goal_difference: 1,
    logo: "https://static.flashscore.com/res/image/data/UudlC76k-6FedhD0P.png",
    losses: 13,
    matches: 34,
    points: 47,
    position: 9,
    team_name: "Cuiaba",
    wins: 13,
  },
  {
    draws: 10,
    goal_difference: 1,
    logo: "https://static.flashscore.com/res/image/data/jBU0jVPq-UPn7aGHL.png",
    losses: 12,
    matches: 34,
    points: 46,
    position: 10,
    team_name: "Sao Paulo",
    wins: 12,
  },
  {
    draws: 8,
    goal_difference: -2,
    logo: "https://static.flashscore.com/res/image/data/4jCqyBoe-8r8ETTNO.png",
    losses: 14,
    matches: 34,
    points: 44,
    position: 11,
    team_name: "Fortaleza",
    wins: 12,
  },
  {
    draws: 14,
    goal_difference: -4,
    logo: "https://static.flashscore.com/res/image/data/WCPVtuUH-Sv3m8l2G.png",
    losses: 11,
    matches: 35,
    points: 44,
    position: 12,
    team_name: "Corinthians",
    wins: 10,
  },
  {
    draws: 10,
    goal_difference: -5,
    logo: "https://static.flashscore.com/res/image/data/p2TzSgBN-ALgHCh57.png",
    losses: 13,
    matches: 34,
    points: 43,
    position: 13,
    team_name: "Internacional",
    wins: 11,
  },
  {
    draws: 10,
    goal_difference: -18,
    logo: "https://static.flashscore.com/res/image/data/hzibzPjC-ALgHCh57.png",
    losses: 14,
    matches: 35,
    points: 43,
    position: 14,
    team_name: "Santos",
    wins: 11,
  },
  {
    draws: 9,
    goal_difference: -8,
    logo: "https://static.flashscore.com/res/image/data/Qw7CsWAN-bam8o1Nj.png",
    losses: 15,
    matches: 35,
    points: 42,
    position: 15,
    team_name: "Vasco",
    wins: 11,
  },
  {
    draws: 8,
    goal_difference: -4,
    logo: "https://static.flashscore.com/res/image/data/IL73beA6-dKUmd286.png",
    losses: 16,
    matches: 35,
    points: 41,
    position: 16,
    team_name: "Bahia",
    wins: 11,
  },
  {
    draws: 11,
    goal_difference: 2,
    logo: "https://static.flashscore.com/res/image/data/dzBBasiT-SjJmyx86.png",
    losses: 13,
    matches: 34,
    points: 41,
    position: 17,
    team_name: "Cruzeiro",
    wins: 10,
  },
  {
    draws: 11,
    goal_difference: -15,
    logo: "https://static.flashscore.com/res/image/data/YqfJ3686-G2OQQubE.png",
    losses: 15,
    matches: 34,
    points: 35,
    position: 18,
    team_name: "Goias",
    wins: 8,
  },
  {
    draws: 5,
    goal_difference: -29,
    logo: "https://static.flashscore.com/res/image/data/zZF6CogT-8f6Hj6B0.png",
    losses: 22,
    matches: 35,
    points: 29,
    position: 19,
    team_name: "Coritiba",
    wins: 8,
  },
  {
    draws: 9,
    goal_difference: -32,
    logo: "https://static.flashscore.com/res/image/data/K2MlyGoe-bXQuKmbC.png",
    losses: 21,
    matches: 34,
    points: 21,
    position: 20,
    team_name: "America MG",
    wins: 4,
  },
];
